---
# tasks file for pah

- name: Find number of hub hosts
  set_fact:
    clustered_mode: ("{{query('inventory_hostnames', 'ansiblehub')}}" | length > 1)

# When in custered mode...
- block:
  - name: Ensure we shared /var/lib/pulp
    assert:
      that:
        automation_hub_shared_pulp is defined

  - name: Make sure /var/lib/pulp exists
    file:
      path: /var/lib/pulp
      state: directory

  - name: Ensure shared mount defined in fstab
    ansible.posix.mount:
      fstype: nfs
      state: mounted
      path: /var/lib/pulp
      src: "{{ automation_hub_shared_pulp }}"

  when:
    clustered_mode|bool

- name: Ensure system fully updated
  package:
    name: '*'
    state: latest

- name: Generate SSH key
  community.crypto.openssh_keypair:
    path: /root/.ssh/id_ed25519
    type: ed25519

- name: Fetch new pubkey
  fetch:
    src: /root/.ssh/id_ed25519.pub
    dest: "/tmp/sshkey-{{ inventory_hostname }}"
    flat: yes

- name: Fetch pubkey from database host if we're in a managed mode
  fetch: 
    src: /root/.ssh/id_ed25519.pub
    dest: "/tmp/sshkey-{{ item }}"
  delegate_to: "{{ item }}"
  loop: "{{query('inventory_hostnames', 'ansibledb')}}"
  when: automation_platform_db_managed

- name: Authorize on all other hub hosts
  ansible.posix.authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '/tmp/sshkey-{{ item }}') }}"
  loop: "{{query('inventory_hostnames','ansiblehub')}}"

- name: Enable Automation Platform repo
  community.general.rhsm_repository:
    name: ansible-automation-platform-2.1-for-rhel-8-x86_64-rpms

# This play will soon be replaced by a 'dnf' module installing the
# installer bundle package.
- name: Put the installer bundle into place on hub host 1 and unzip
  unarchive:
    src: "{{ automation_platform_setup }}.tar.gz"
    creates: "/root/{{ automation_platform_setup }}/inventory"
    dest: /root/
  run_once: yes
  
- name: Remove the localhost line for automationcontroller from inventory
  lineinfile:
    line: "localhost ansible_connection=local"
    state: absent
    path: "/root/{{ automation_platform_setup }}/inventory"
    backup: yes
  run_once: yes

- name: Ensure hub hosts present in inventory
  lineinfile:
    insertafter: '\[automationhub\]'
    regexp: '^{{ item }}'
    line: "{{ item }}"
    state: present
    path: "/root/{{ automation_platform_setup }}/inventory"
    firstmatch: yes
  loop: "{{query('inventory_hostnames', 'ansiblehub')}}"
  run_once: yes

- name: Ensure DB target host in database section
  lineinfile:
    insertafter: '[database]'
    line: "{{query('inventory_hostnames', 'ansibledb')}}"
    state: present
    path: "/root/{{ automation_platform_setup }}/inventory"
  when: automation_platform_db_managed
  run_once: yes

- name: Ensure admin password set
  lineinfile:
    regexp: '^automationhub_admin_password'
    line: "automationhub_admin_password='{{ ansible_admin_pass }}'"
    state: present
    path: "/root/{{ automation_platform_setup }}/inventory"
  run_once: yes

- name: Ensure pg_host entry correct
  lineinfile:
    regexp: '^automationhub_pg_host='
    line: "automationhub_pg_host='{{query('inventory_hostnames', 'ansibledb') | first }}'"
    state: present
    path: "/root/{{ automation_platform_setup }}/inventory"
  run_once: yes

- name: Ensure correct pg_port entry
  lineinfile:
    regexp: '^automationhub_pg_port='
    line: "automationhub_pg_port='{{ automation_platform_db_port | default('5432') }}'"
    state: present
    path: "/root/{{ automation_platform_setup }}/inventory"
  run_once: yes

- name: Ensure correct pg_username entry
  lineinfile:
    regexp: '^automationhub_pg_username='
    line: "automationhub_pg_username='{{ pah_db_user | default('awx') }}'"
    state: present
    path: "/root/{{ automation_platform_setup }}/inventory"
  run_once: yes

- name: Ensure correct pg_password entry
  lineinfile:
    regexp: '^automationhub_pg_password='
    line: "automationhub_pg_password='{{ pah_db_pass }}'"
    state: present
    path: "/root/{{ automation_platform_setup }}/inventory"
  run_once: yes

- name: Ensure correct registry_username entry
  lineinfile:
    regexp: '^registry_username='
    line: "registry_username='{{ controller_reg_username }}'"
    state: present
    path: "/root/{{ automation_platform_setup }}/inventory"
  run_once: yes

- name: Ensure correct registry_password entry
  lineinfile:
    regexp: '^registry_password='
    line: "registry_password='{{ controller_reg_password }}'"
    state: present
    path: "/root/{{ automation_platform_setup }}/inventory"
  run_once: yes

- name: Clean up keys from tmp directory
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - "/tmp/sshkey-*"

- name: Ensure Ansible package installed
  package:
    name: ansible-core
    state: present
